"""Public API boundary tests."""

import cybersecgpt.tokenizer as tokenizer


def test_public_api_is_explicit() -> None:
    assert tokenizer.__all__ == [
        "AlgorithmBenchmarkReport",
        "BENCHMARK_BPE_MERGE_BUDGET",
        "BENCHMARK_MAX_TRAINING_BYTES",
        "BENCHMARK_POLICY_ID",
        "BENCHMARK_SCHEMA_VERSION",
        "BENCHMARK_VOCABULARY_LIMIT",
        "BPE_ALGORITHM_ID",
        "BpeMerge",
        "BpeTrainingFinishStatus",
        "ByteBpeCandidate",
        "ByteBpeTrainingConfig",
        "ByteBpeTrainingResult",
        "BYTE_REFERENCE_ALGORITHM_ID",
        "ByteUnigramCandidate",
        "ByteUnigramTrainingConfig",
        "ByteUnigramTrainingResult",
        "CandidateEvaluationReport",
        "CandidateBenchmarkEvidence",
        "CandidateSampleMetrics",
        "ByteBpeStreamingEncoder",
        "MAX_IDENTIFIER_LENGTH",
        "MAX_STREAM_CHUNK_BYTES",
        "MAX_STREAM_CHUNKS",
        "MAX_EVALUATION_SAMPLES",
        "MAX_TEXT_BYTES",
        "MAX_TOKEN_COUNT",
        "MAX_VOCABULARY_SIZE",
        "UTF8_BYTE_REFERENCE_FINGERPRINT",
        "DecodeRequest",
        "DecodeResult",
        "DomainAggregate",
        "EncodeRequest",
        "EncodeResult",
        "EvaluationDomain",
        "EvaluationManifest",
        "EvaluationSample",
        "ExactRatio",
        "FinishStatus",
        "ReferenceSampleMetrics",
        "SpecialToken",
        "StreamingDeadlineError",
        "StreamingState",
        "StreamingStateError",
        "TokenizerContractError",
        "TokenizerDescriptor",
        "Utf8ByteReferenceTokenizer",
        "UnigramTrainingFinishStatus",
        "UNIGRAM_ALGORITHM_ID",
        "evaluate_candidate",
        "evaluate_utf8_byte_reference",
        "run_algorithm_benchmark",
        "select_algorithm",
        "train_byte_bpe_candidate",
        "train_byte_unigram_candidate",
    ]
